### ISSUE TITLE
Will this project be maintained?

### ISSUE THREAD

**Issue by yamaton** [mariusvniekerk/condax#41]
Hi @mariusvniekerk. I worked on a fork[^1] of `condax` recently, and I'm hoping to publish it to pypi and conda-forge in the near future. I'd love to feedback features added to the fork as PRs if you have time to maintain this project. Would you share your plan on this project if you don't mind? Thanks.

[^1]: https://github.com/yamaton/condax

**Comment by mariusvniekerk** [comment]
I am still maintaining this, but would love some co-maintainers

**Comment by abrahammurciano** [comment]
Hey @mariusvniekerk,

@yamaton and myself have been working on adding lots of features (similar to the ones found in pipx, e.g. injecting other packages into envs) and refactoring some of the code.

We'd like to co-maintain this project so we can integrate our changes into it and release v1.0.0 instead of creating a new forked package.

You can see our progress so far in @yamaton's fork. Let us know what you think!

**Comment by cafhach** [comment]
@abrahammurciano Did you come to an agreement? The package still appears unmaintained?

**Comment by abrahammurciano** [comment]
@cafhach nope. I don't use conda much anymore and I lost interest
